const CLUBS={"club-a":{name:"Club A",hint:"Downtown demo venue",brand:"CLUB A x JADZ ADCO"},"club-b":{name:"Club B",hint:"VIP lounge demo venue",brand:"CLUB B x JADZ ADCO"},"jadz":{name:"Jadz Demo",hint:"Shared master demo",brand:"JADZ ADCO"}};
const TEMPLATES=[{id:"neon",name:"Neon Birthday",scope:"Shared",className:"neon"},{id:"gold",name:"Gold VIP",scope:"Shared",className:"gold"},{id:"ice",name:"Ice Bottle Service",scope:"Club-specific",className:"ice"},{id:"fire",name:"Fire Celebration",scope:"Club-specific",className:"fire"}];
function qs(n,f=""){const u=new URL(location.href);return u.searchParams.get(n)||f}function clubId(){return qs("club","jadz").toLowerCase()}function getClub(){return CLUBS[clubId()]||CLUBS.jadz}function key(n){return`jadz_${clubId()}_${n}`}function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function writeJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}function displayUrl(p){const u=new URL("./display.html",location.href);u.searchParams.set("club",clubId());if(p){u.searchParams.set("main",p.mainText||"");u.searchParams.set("sub",p.subText||"");u.searchParams.set("template",p.template||"neon");u.searchParams.set("media",p.mediaUrl||"")}return u.href}let selectedTemplate="neon";
function initClientPortal(){const c=getClub();clubName.textContent=c.name;clubHint.textContent=c.hint;renderTemplates();updatePreview();["mainText","subText","mediaUrl"].forEach(id=>document.getElementById(id).addEventListener("input",updatePreview))}
function demoLogin(p){authCard.classList.add("hidden");composer.classList.remove("hidden");submitStatus.textContent=`Signed in with ${p}. Create your shoutout below.`}
function renderTemplates(){const g=templateGrid;g.innerHTML="";TEMPLATES.forEach(t=>{const d=document.createElement("div");d.className=`template ${t.className} ${t.id===selectedTemplate?"selected":""}`;d.innerHTML=`<div class="name">${t.name}</div><div class="tag">${t.scope}</div>`;d.onclick=()=>{selectedTemplate=t.id;renderTemplates();updatePreview()};g.appendChild(d)})}
function collectPayload(status="pending"){return{id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),club:clubId(),template:selectedTemplate,mainText:mainText.value.trim()||"SHOUTOUT!",subText:subText.value.trim()||"",mediaUrl:mediaUrl.value.trim(),status,createdAt:new Date().toISOString()}}
function updatePreview(){previewFrame.src=displayUrl(collectPayload("preview"))}function submitShoutout(){const p=collectPayload("pending"),q=readJSON(key("queue"),[]);q.unshift(p);writeJSON(key("queue"),q);submitStatus.textContent="Submitted. Waiting for club admin approval."}
function initAdminPortal(){clubName.textContent=getClub().name}function adminLogin(){if(adminPassword.value!=="admin123"){adminStatus.textContent="Wrong demo password.";return}document.getElementById("adminLogin").classList.add("hidden");adminPanel.classList.remove("hidden");renderQueue()}
function renderQueue(){const live=readJSON(key("live"),null);liveFrame.src=live?displayUrl(live):displayUrl({mainText:"NO APPROVED SHOUTOUT YET",subText:"Approve one from the queue",template:"neon"});displayLink.href=live?displayUrl(live):displayUrl();const q=readJSON(key("queue"),[]);if(q.length===0){queueList.innerHTML=`<p class="sub">No pending shoutouts yet. Submit one from the client portal.</p>`;return}queueList.innerHTML="";q.forEach((item,idx)=>{const d=document.createElement("div");d.className="queue-item";d.innerHTML=`<strong>${esc(item.mainText)}</strong><p>${esc(item.subText)}</p><small>Template: ${item.template} • ${new Date(item.createdAt).toLocaleString()}</small><div class="queue-actions"><button class="approve" onclick="approveItem(${idx})">Approve & Push Live</button><button class="reject" onclick="rejectItem(${idx})">Reject</button><a class="buttonlike" target="_blank" href="${displayUrl(item)}">Preview</a></div>`;queueList.appendChild(d)})}
function approveItem(i){const q=readJSON(key("queue"),[]),item=q.splice(i,1)[0];item.status="approved";item.approvedAt=new Date().toISOString();writeJSON(key("queue"),q);writeJSON(key("live"),item);renderQueue()}function rejectItem(i){const q=readJSON(key("queue"),[]);q.splice(i,1);writeJSON(key("queue"),q);renderQueue()}
function initDisplayPage(){const c=getClub(),live=readJSON(key("live"),null),p={mainText:qs("main",live?.mainText||"WELCOME TO THE SHOW"),subText:qs("sub",live?.subText||"Scan the QR code to send a shoutout"),template:qs("template",live?.template||"neon"),mediaUrl:qs("media",live?.mediaUrl||"")};displayBrand.textContent=c.brand;displayCanvas.classList.remove("gold","ice","fire");if(p.template!=="neon")displayCanvas.classList.add(p.template);displayMain.textContent=p.mainText;displaySub.textContent=p.subText;if(p.mediaUrl){mediaSlot.classList.remove("hidden");const v=/\.(mp4|webm|ogg)(\?|$)/i.test(p.mediaUrl);mediaSlot.innerHTML=v?`<video src="${p.mediaUrl}" autoplay muted loop playsinline></video>`:`<img src="${p.mediaUrl}" alt="">`}setInterval(()=>{const n=readJSON(key("live"),null);if(n&&!qs("main","")){displayMain.textContent=n.mainText;displaySub.textContent=n.subText}},5000)}function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
