/* notification-center.js v28.4 */
(function(){
"use strict";
function byId(id){return document.getElementById(id);}
if(window.JADZ_NOTIFICATION_CENTER_LOADED)return;
window.JADZ_NOTIFICATION_CENTER_LOADED=true;
function shell(){if(byId("jadzGlobalStatusBar"))return;let b=document.createElement("div");b.id="jadzGlobalStatusBar";b.className="jadz-global-status-bar hidden";b.innerHTML='<a id="jadzInboxLink" href="./patron-portal.html?tab=messages&v=28.13">Messages (0/0)</a><a id="jadzChatsLink" href="./patron-portal.html?tab=chats&v=28.13">Chats (0/0)</a><a id="jadzNotificationsLink" href="./patron-portal.html?tab=messages&v=28.13">Notifications (0)</a>';document.body.appendChild(b);}
async function counts(u){let o={tm:0,um:0,tc:0,uc:0,un:0};if(!u||!window.firebase||!firebase.firestore)return o;let db=firebase.firestore();try{let s=await db.collection("messages").where("recipientUid","==",u.uid).limit(1000).get();o.tm=s.size;s.forEach(d=>{if(!d.data().read)o.um++;});}catch(e){}try{let s=await db.collection("chatRooms").where("participants","array-contains",u.uid).limit(1000).get();o.tc=s.size;s.forEach(d=>{o.uc+=Number((d.data().unreadCounts||{})[u.uid]||0);});}catch(e){}try{let s=await db.collection("inboxNotifications").where("recipientUid","==",u.uid).limit(1000).get();s.forEach(d=>{if(!d.data().read)o.un++;});}catch(e){}return o;}
async function update(u){shell();let b=byId("jadzGlobalStatusBar");if(!b)return;if(!u||location.pathname.endsWith("/patron-portal.html")){b.classList.add("hidden");return;}let c=await counts(u);b.classList.remove("hidden");byId("jadzInboxLink").textContent=`Messages (${c.um}/${c.tm})`;byId("jadzChatsLink").textContent=`Chats (${c.uc}/${c.tc})`;byId("jadzNotificationsLink").textContent=`Notifications (${c.un})`;}
document.addEventListener("DOMContentLoaded",()=>{shell();let w=setInterval(()=>{try{if(window.firebase&&firebase.auth){clearInterval(w);firebase.auth().onAuthStateChanged(u=>{update(u);if(u)setInterval(()=>update(u),60000);});}}catch(e){}},250);});
})();